tbl_vida_util_pecas = [
    {
        "field": "nome_peca",
        "headerName": "NOME DA PEÇA",
        "pinned": "left",
        "minWidth": 200,
        "type": ["numericColumn"],
    },
    {"field": "data_ultima_troca", "headerName": "DATA ÚLTIMA TROCA", "pinned": "left", "minWidth": 450},
    {
        "field": "km_ultima_troca",
        "headerName": "KM DA ULTIMA TROCA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "maxWidth": 200,
        "filter": "agNumberColumnFilter",
        "type": ["numericColumn"],
    },
    {
        "field": "os_ultima_troca",
        "headerName": "OS ÚLTIMA TROCA",
        "filter": "agNumberColumnFilter",
        "maxWidth": 200,
        "type": ["numericColumn"],
    },
    {
        "field": "valor_total",
        "headerName": "VALOR TOTAL",
        "filter": "agNumberColumnFilter",
        "maxWidth": 200,
        "valueFormatter": {"function": "'R$' + params.value.toLocaleString('pt-BR')"},
        "type": ["numericColumn"],
    },
    {
        "field": "valor_por_unidade",
        "headerName": "VALOR POR UNIDADE",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "valueFormatter": {"function": "'R$' + params.value.toLocaleString('pt-BR')"},
        "maxWidth": 200,
        "type": ["numericColumn"],
    },
]